---
title: "Sparse Matrices"
output: html_document
---

Try out various sparse matrix formats

```{r}
library(nnls)
library(pracma)
library(magrittr)
library(Matrix)

# nnls where X is sparse
nnlsSp <- function(X, y, tol = 1e-4) {
  X <- Matrix(X, sparse = TRUE)
  y <- Matrix(y)
  ip <- t(y) %*% X
  corr <- max(ip)
  inds <- order(-ip)[1]
  mags <- 0
  while (corr > tol) {
    xs <- X[, inds, drop = FALSE]
    ssp <- as.numeric(solve(t(xs) %*% xs, t(xs) %*% y))
    while(min(ssp) < 0) {
      temp <- which((ssp - mags) < 0)
      alpha <- min(-mags[temp]/(ssp[temp] - mags[temp]) )
      mags <- mags + alpha * (ssp - mags)
      ind <- order(mags)[1]
      inds <- inds[-ind]
      xs <- X[, inds, drop = FALSE]
      mags <- mags[-ind]
      ssp <- as.numeric(solve(t(xs) %*% xs, t(xs) %*% y))
    }
    mags <- ssp
    r <- y - xs %*% mags
    ip <- t(r) %*% X
    corr <- max(ip)
    ind <- order(-ip)[1]
    if (! ind %in% inds) {
      inds <- c(inds, ind)
      mags <- c(mags, 0)  
    } else {
      corr <- 0
    }
    #c(min(ssp), corr)
  }
  beta <- numeric(dim(X)[2])
  beta[inds] <- mags
  #yh1 <- X %*% Matrix(beta)
  #yh2 <- X[, inds] %*% mags
  #Norm(as.numeric(yh1 - yh2))
  beta
}
```

```{r}
n <- 50
v <- 100
p <- 60
X <- randn(n, p)
B <- abs(randn(p, v))
Y <- X %*% B
Yvec <- Y %>% as.numeric
Xbig <- eye(v) %x% X
Xsp <- Matrix(X, sparse = TRUE)
eyeSp <- Matrix(eye(v), sparse = TRUE)
XbigSp <- eyeSp %x% Xsp
t1 <- proc.time()
#ip <- t(Yvec) %*% Xbig 
sol <- nnls(Xbig, Yvec)$x
t2 <- proc.time()
#ipSp <- as.numeric(Matrix(t(Yvec)) %*% XbigSp)
sol2 <- nnls(XbigSp, Matrix(Yvec))$x
t3 <- proc.time()
sol3 <- nnlsSp(XbigSp, Matrix(Yvec))
t4 <- proc.time()
# time using Naive
(t2 - t1)[3]
# time using sparse
(t3 - t2)[3]
# time using custom
(t4 - t3)[3]
Norm(sol - sol3)
Norm(sol - sol2)
```
